### ISSUE TITLE
Fix macOS builds

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy-template#48]
Need to sanity check that they look fine and can be run.

Windows and Linux builds have been tested, and the web build can be tested by anyone on itch.io.

**Comment by janhohenheim** [comment]
<img width="913" alt="image" src="https://github.com/TheBevyFlock/bevy-template/assets/9047632/42df9d19-29c0-4114-a724-e940c8df2a59">

Intel does not work.
I suggest using the build used by https://github.com/NiklasEi/bevy_game_template, that one works and also produces a single binary for macOS. It's bigger because it includes both M1 and Intel builds, but the heavy stuff is the assets anyways and not the binaries themselves, so I'd prefer it from a usability standpoint.
